### PR TITLE
Fix Win/Loss detection

### PR DESCRIPTION
**Pull request by hexbyt3**
+ Fix Win/Loss detection
+ Fix RaidCount Increment

### CODE REVIEW

**Comment by lGodHatesMel** [comment]
Adding  "CountRaids" just to log wins and loses isnt needed. It was removed because it wasnt needed, so no point adding it back just for that 1 thing. There is a better/easier way of doing it.

**Comment by hexbyt3** [comment]
Interesting.

**Comment by hexbyt3** [comment]
> Adding "CountRaids" just to log wins and loses isnt needed. It was removed because it wasnt needed, so no point adding it back just for that 1 thing. There is a better/easier way of doing it.

You should do a PR and fix then, because it ain't workin dawg.

**Comment by zyro670** [comment]
Used different method

**Pull request closed without merging**
